---
title: "attempt"
author: "Colin Fay"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{attempt}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  error = TRUE,
  collapse = TRUE,
  comment = "#>"
)
```

# {attempt}

A Friendlier Condition Handler for R, based on {purrr} mappers and {rlang}.

{attempt} is designed to handle the cases when something / someone attempts to do something it shouldn't. For example : 

+ attempt to run a `log("a")` (error)
+ attempt to connect to a web API without an internet connexion running (error)
+ attempt to `paste()` `"good morning` and `iris` (message/warning)
+ ... 

{attempt} provides several condition handlers, from try catch to simple message printing. 

# Install

```{r eval = FALSE}
devtools::install_github("ColinFay/attempt")
```

# Reference 

## attempt 

`attempt` is a wrapper around base `try` that allows you to insert a custom messsage on error. 

```{r eval = FALSE}
library(attempt)
attempt(log("a"), msg = "Nop !")
#> Error : Nop !
```

You can make it verbose (i.e. returning the expression): 

```{r eval = FALSE}
attempt(log("a"), msg = "Nop !", verbose = TRUE)
#> Error in log("a") : Nop !
```



## try catch

You can write a try catch with these params : 

+ `expr` the expression to be evaluated 
+ `.e` a one side formula or a function evaluated when an error occurs
+ `.w` a one side formula or a function evaluated when a warning occurs
+ `.f` a one side formula or an expression which is always evaluated before returning or exiting

### With mappers 

```{r}
try_catch(log("a"), 
          .e = ~ paste0("There is an error: ", .x), 
          .w = ~ paste0("This is a warning: ", .x))

try_catch(log("a"), 
          .e = ~ print(.x), 
          .w = ~ print(.x))

try_catch(matrix(1:3, nrow= 2), 
          .e = ~ print(.x), 
          .w = ~ print(.x))

try_catch(2 + 2 , 
          .f = ~ print("Using R for addition... ok I'm out!"))
```

As usual, the handlers are set only if you call them : 

```{r}
try_catch(matrix(1:3, nrow = 2), .e = ~ print("error"))
```

```{r}
try_catch(matrix(1:3, nrow = 2), .w = ~ print("warning"))
```


### Traditionnal way 

{attempt} is flexible in how you can specify your arguments. 

You can, as you do with {base} `tryCatch`, use a plain old function: 

```{r}
try_catch(log("a"), 
          .e = function(e){
            print(paste0("There is an error: ", e))
            print("Ok, let's save this")
            time <- Sys.time()
            a <- paste("+ At",time, ", \nError:",e)
            # write(a, "log.txt", append = TRUE) # commented to prevent from log.txt creation on your machine
            print(paste("log saved on log.txt at", time))
            print("let's move on now")
          })
```

You can even mix both: 

```{r}
try_catch(log("a"), 
          .e = function(e){
            paste0("There is an error: ", e)
          },
          .f = ~ print("I'm not sure you can do that pal !"))
```

### try_catch_df 

`try_catch_df` returns a tibble with the call, the error message if any, the warning message if any, and the value of the evaluated expression or "error". 

```{r}
res_log <- try_catch_df(log("a"))
res_log
res_log$value

res_matrix <- try_catch_df(matrix(1:3, nrow = 2))
res_matrix
res_matrix$value

res_success <- try_catch_df(log(1))
res_success
res_success$value
```

### map try_catch

`map_try_catch` and `map_try_catch_df` allow you to map on a list of arguments `l`, to be evaluated by the function in `fun`. 

```{r}
map_try_catch(l = list(1, 3, "a"), fun = log, .e = ~ .x)

map_try_catch_df(list(1,3,"a"), log)
```

## silently 

`silently` transforms a function so that when you call this new function, it returns nothing unless there is an error or a warning (contrary to `attempt` that returns the result). In a sense, the new function stay silent unless error or warning.

```{r}
silent_log <- silently(log)
silent_log(1)
silent_log("a")
```


## warnings and messages

The `stop_if`, `warn_if` and `message_if` are easy to use functions that send an error, a warning or a message if a condition is met. Each function has its counterpart with `_not`. That returns a message if the condition is not met.

`stop_if_not` is quite the same as `assert_that` from the {assertthat} package, except that it can takes mappers. It is not the same as base `stopifnot()`, as it doesn't take a list of expression.

These functions are also flexible as you can pass base predicates (is.numeric, is.character...), a custom one built with mappers, or even your own testing function.

You can either choose a custom message or just let the built-in messages be printed:

```{r}
x <- 12
# Stop if .x is numeric
stop_if(.x = x, 
        .p = is.numeric)

y <- "20"
# stop if .x is not numeric
stop_if_not(.x = y, 
            .p = is.numeric, 
            msg = "y should be numeric")
a  <- "this is not numeric"
# Warn if .x is charcter
warn_if(.x = a, 
        .p = is.character)

b  <- 20
# Warn if .x is not equal to 10
warn_if_not(.x = b, 
        .p = ~ .x == 10 , 
        msg = "b should be 10")

c <- "a"
# Message if c is a character
message_if(.x = c, 
           .p = is.character, 
           msg = "You entered a character element")

# Build more complex predicates
d <- 100
message_if(.x = d, 
           .p = ~ sqrt(.x) < 42, 
           msg = "The square root of your element must be more than 42")

# Or, if you're kind of old school, you can still pass classic functions

e <- 30
message_if(.x = e, 
           .p = function(vec){
             return(sqrt(vec) < 42)
           }, 
           msg = "The square root of your element must be more than 42")
```

If you have a function with no arguments, you can pass a dot `.` as first argument : 

```{r}
false <- function() return(FALSE)
true <- function() return(TRUE)
stop_if(., true, msg = "Nop")

warn_if_not(., false, 
            msg = "Carefull!")

message_if(., true, 
            msg = "Huray \\o/")
```

That can come really handy inside a function : 

```{r}
my_fun <- function(x){
  warn_if(x, 
          ~ ! is.character(.x), 
          msg =  "x is not a character vector. \nThe output may not be what you're expecting.")
  paste(x, "is the value.")
}

my_fun(head(iris))
```

### none, all, any

`stop_if`, `warn_if` and `message_if` all have complementary tests with `_all`, `_any` and `_none`. They take a list as first argument, and a predicate. They test if any, all or none of the elements validate the predicate. 

```{r}
stop_if_any(iris, is.factor, msg = "Factors here. This might be due to stringsAsFactors")

warn_if_none(1:10, ~ .x < 0, msg = "You need to have at least one number under zero")

message_if_all(1e3:1e4, ~ .x > 1e2, msg = "All your number are above 1e2. This may take some time to compute.")
```


# Misc

## Acknowledgments

Thank to [Romain](http://romain.rbind.io/) for the name suggestion. 

## Contact

Questions and feedbacks [welcome](mailto:contact@colinfay.me)!

You want to contribute ? Open a [PR](https://github.com/ColinFay/attempt/pulls) :) If you encounter a bug or want to suggest an enhancement, please [open an issue](https://github.com/ColinFay/attempt/issues).
